configs:
  - acm.yaml
  - hms.yaml
  - ocm-rosa.yaml
  - ocm-rosa-hcp.yaml
  - ocm-osd-gcp.yaml
  - ocm-fm.yaml
  - ocm-am.yaml
  - ossm.yaml
  - srvcli.yaml
  - srvcom.yaml
  - srvke.yaml
  - srvks.yaml
  - srvocf.yaml
  - threescale.yaml
  - tracing.yaml
