OCM-FM:
  blocker: "project = 'OCM' AND ( (labels  = TestBlocker AND type = Bug and Status not in (Closed,Verified)) )  AND component= 'fleet-manager'"
  critical-blocker: "project = 'OCM' AND type = Bug and Status not in (Closed,Verified) AND ((labels  = release-blocker ) or (priority = Blocker)) AND component = 'fleet-manager' "
